# Generated by Django 3.2.11 on 2022-01-15 13:19

from django.db import migrations
import test_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wizard',
            name='coordinates',
            field=test_app.models.CoordinatesField(max_length=100, null=True),
        ),
    ]
