# Generated by Django 4.0.2 on 2022-02-22 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("test_app", "0002_auto_20220118_1400"),
    ]

    operations = [
        migrations.AddField(
            model_name="patronus",
            name="memory",
            field=models.OneToOneField(
                db_column="flashback_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="test_app.memory",
            ),
        ),
        migrations.AlterField(
            model_name="patronus",
            name="color",
            field=models.CharField(db_column="colour", max_length=50, null=True),
        ),
    ]
