# Generated by Django 4.1.1 on 2022-09-09 18:30

import django.db.models.deletion
from django.db import migrations, models

import drf_kit.models.diff_models
import drf_kit.models.file_models


class Migration(migrations.Migration):
    dependencies = [
        ("test_app", "0004_newspaper_roomofrequirement_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("deleted_at", models.DateTimeField(blank=True, default=None, null=True, verbose_name="deleted at")),
                ("title", models.CharField(default="?", max_length=30)),
                ("newspaper", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="test_app.newspaper")),
            ],
            options={
                "ordering": ("-updated_at",),
                "get_latest_by": "updated_at",
                "abstract": False,
            },
            bases=(
                drf_kit.models.diff_models.ModelDiffMixin,
                drf_kit.models.file_models.BoundedFileMixin,
                models.Model,
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["updated_at"], name="test_app_ar_updated_d2ab7e_idx"),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["deleted_at"], name="test_app_ar_deleted_399f7d_idx"),
        ),
    ]
