# Generated by Django 4.2.1 on 2023-07-20 13:37

import django.db.models.deletion
from django.db import migrations, models

import drf_kit.models.diff_models
import drf_kit.models.file_models


class Migration(migrations.Migration):
    dependencies = [
        ("test_app", "0008_beastowner_beastownership_beastowner_beasts_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BeastCategory",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("deleted_at", models.DateTimeField(blank=True, default=None, null=True, verbose_name="deleted at")),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ("-updated_at",),
                "get_latest_by": "updated_at",
                "abstract": False,
                "indexes": [
                    models.Index(fields=["updated_at"], name="test_app_be_updated_e88378_idx"),
                    models.Index(fields=["deleted_at"], name="test_app_be_deleted_5c1b02_idx"),
                ],
            },
            bases=(
                drf_kit.models.diff_models.ModelDiffMixin,
                drf_kit.models.file_models.BoundedFileMixin,
                models.Model,
            ),
        ),
        migrations.AddField(
            model_name="beast",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="test_app.beastcategory",
            ),
        ),
    ]
