# Generated by Django 4.2.1 on 2023-07-20 18:26

import django.db.models.deletion
from django.db import migrations, models

import drf_kit.fields


class Migration(migrations.Migration):
    dependencies = [
        ("test_app", "0009_beastcategory_beast_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="exclusivearticle",
            name="slug",
            field=drf_kit.fields.SlugifyField(null=True),
        ),
        migrations.AlterField(
            model_name="beast",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="beasts",
                to="test_app.beastcategory",
            ),
        ),
    ]
