# Generated by Django 5.0.6 on 2024-06-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("test_app", "0011_trainingpitch_reservation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="beast",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
