# Generated by Django 5.0.6 on 2024-07-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("test_app", "0012_beast_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="wizard",
            name="minimum_age",
            field=models.GeneratedField(
                db_persist=True, expression=models.Value(11), output_field=models.IntegerField()
            ),
        ),
    ]
